In [2]:
import cv2
import os
import numpy as np

In [3]:
files = os.listdir('1')
img = cv2.imread("1/1 (12).jpg")

In [4]:
cv2.imshow('ax',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
img = cv2.imread('1/1 (1).jpg' )
img2 = cv2.resize(img,(8,32))
img3 = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
img4 = img3.flatten()

In [6]:
img4.shape

(256,)

In [5]:
files = os.listdir('1')
x = np.empty((0,256))
y = np.array([])
for filename in files:
    img = cv2.imread('1/' + filename)
    img2 = cv2.resize(img,(8,32))
    img3 = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
    img4 = img3.flatten()
    x = np.append(x,[img4],axis=0)  
    y = np.append(y,1)

files2 = os.listdir('2')


for filename in files2:
    img = cv2.imread('2/' + filename)
    img2 = cv2.resize(img,(8,32))
    img3 = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
    img4 = img3.flatten()
    x = np.append(x,[img4],axis=0)  
    y = np.append(y,2)

files3 = os.listdir('3')


for filename in files3:
    img = cv2.imread('3/' + filename)
    img2 = cv2.resize(img,(8,32))
    img3 = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
    img4 = img3.flatten()
    x = np.append(x,[img4],axis=0)  
    y = np.append(y,3)

files4 = os.listdir('4')


for filename in files4:
    img = cv2.imread('4/' + filename)
    img2 = cv2.resize(img,(8,32))
    img3 = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
    img4 = img3.flatten()
    x = np.append(x,[img4],axis=0)  
    y = np.append(y,4)

files5 = os.listdir('5')


for filename in files5:
    img = cv2.imread('5/' + filename)
    img2 = cv2.resize(img,(8,32))
    img3 = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
    img4 = img3.flatten()
    x = np.append(x,[img4],axis=0)  
    y = np.append(y,5)

files6 = os.listdir('6')


for filename in files6:
    img = cv2.imread('6/' + filename)
    img2 = cv2.resize(img,(8,32))
    img3 = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
    img4 = img3.flatten()
    x = np.append(x,[img4],axis=0)  
    y = np.append(y,6)

files7 = os.listdir('7')


for filename in files7:
    img = cv2.imread('7/' + filename)
    img2 = cv2.resize(img,(8,32))
    img3 = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
    img4 = img3.flatten()
    x = np.append(x,[img4],axis=0)  
    y = np.append(y,7)


files8 = os.listdir('8')


for filename in files8:
    img = cv2.imread('8/' + filename)
    img2 = cv2.resize(img,(8,32))
    img3 = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
    img4 = img3.flatten()
    x = np.append(x,[img4],axis=0)  
    y = np.append(y,8)

files9 = os.listdir('9')


for filename in files9:
    img = cv2.imread('9/' + filename)
    img2 = cv2.resize(img,(8,32))
    img3 = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
    img4 = img3.flatten()
    x = np.append(x,[img4],axis=0)  
    y = np.append(y,9)



In [8]:
x.shape

(3101, 256)

In [6]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test = train_test_split(x , y , test_size=0.2)

In [8]:
model = linear_model.LogisticRegression()

In [9]:
model.fit(X_train,y_train)
out = model.predict(X_test)

c:\Users\ragab\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [10]:
out

array([9., 7., 1., 4., 5., 1., 1., 3., 6., 2., 4., 4., 7., 6., 2., 8., 5.,
       4., 8., 3., 7., 2., 6., 6., 3., 6., 6., 1., 7., 3., 7., 4., 5., 1.,
       3., 6., 5., 4., 1., 6., 1., 1., 8., 2., 8., 3., 1., 2., 7., 6., 8.,
       4., 5., 7., 3., 4., 2., 1., 4., 2., 5., 1., 4., 7., 2., 9., 2., 9.,
       8., 3., 5., 4., 5., 4., 6., 2., 8., 5., 4., 6., 8., 8., 8., 9., 2.,
       1., 6., 7., 1., 3., 5., 1., 1., 5., 7., 8., 5., 5., 5., 6., 5., 1.,
       6., 6., 9., 9., 1., 9., 8., 9., 2., 1., 1., 9., 2., 2., 3., 7., 3.,
       1., 9., 9., 3., 5., 4., 3., 3., 6., 4., 3., 8., 6., 4., 8., 1., 7.,
       2., 6., 2., 5., 7., 1., 1., 3., 2., 5., 2., 7., 4., 1., 6., 6., 9.,
       4., 9., 9., 5., 7., 7., 2., 1., 5., 5., 8., 7., 3., 9., 8., 1., 3.,
       9., 2., 3., 6., 1., 9., 6., 4., 2., 9., 4., 1., 2., 5., 6., 6., 7.,
       9., 3., 3., 3., 4., 3., 1., 6., 8., 1., 8., 6., 2., 2., 7., 6., 9.,
       7., 8., 5., 7., 8., 3., 5., 2., 1., 8., 1., 2., 8., 3., 2., 1., 8.,
       9., 8., 9., 8., 8.

In [11]:
y_test

array([9., 7., 1., 4., 5., 1., 1., 3., 6., 2., 4., 4., 7., 6., 2., 8., 5.,
       4., 8., 3., 7., 7., 6., 6., 3., 6., 4., 9., 7., 3., 2., 4., 1., 1.,
       3., 4., 5., 4., 1., 6., 7., 1., 8., 2., 8., 3., 1., 2., 7., 2., 8.,
       2., 5., 7., 4., 4., 2., 1., 4., 2., 5., 2., 4., 7., 3., 9., 2., 1.,
       8., 3., 2., 4., 5., 4., 6., 2., 8., 5., 3., 6., 8., 8., 8., 9., 2.,
       1., 6., 7., 1., 3., 5., 1., 1., 5., 7., 8., 5., 5., 5., 6., 5., 1.,
       6., 6., 9., 9., 1., 9., 8., 3., 2., 1., 1., 9., 2., 2., 3., 7., 3.,
       1., 9., 9., 3., 5., 9., 3., 3., 6., 4., 3., 8., 6., 4., 8., 1., 7.,
       2., 9., 2., 5., 7., 2., 1., 3., 2., 5., 2., 7., 4., 9., 6., 6., 9.,
       4., 9., 9., 5., 7., 7., 8., 1., 5., 5., 8., 7., 3., 9., 8., 1., 3.,
       9., 2., 4., 6., 1., 9., 6., 4., 7., 9., 4., 1., 2., 5., 6., 6., 7.,
       9., 3., 3., 3., 4., 3., 1., 6., 8., 1., 8., 6., 2., 2., 7., 6., 9.,
       7., 8., 5., 7., 8., 3., 5., 2., 1., 8., 3., 2., 8., 9., 2., 1., 8.,
       9., 8., 9., 8., 8.

In [15]:
x1 = np.empty((0,256))
img = cv2.imread('4/4 (111).jpg')
imgx = cv2.imshow('ax',img)
img2 = cv2.resize(img,(8,32))
img3 = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
img4 = img3.flatten()
x1 = np.append(x1,[img4],axis=0)  

In [16]:
natijeh = model.predict(x1)

In [17]:
natijeh

array([3.])